### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by songshenma** [deepcs233/jieba_fast#5]
Building prefix dict from the default dictionary ...
Loading model from cache /var/folders/8t/z__z7fgj5rnfxbvmysdv7_rw0000gn/T/jieba.cache
Loading model cost 0.919 seconds.
Prefix dict has been built succesfully.
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa3 in position 0: invalid start byte

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/macos/PycharmProjects/tensorflow/NLPTools/jiebaParallel.py", line 18, in <module>
    words = "/ ".join(jieba.lcut(content))#默认精确模式
  File "/Users/macos/anaconda3/envs/tensorflow/lib/python3.6/site-packages/jieba_fast/__init__.py", line 340, in lcut
    return list(self.cut(*args, **kwargs))
  File "/Users/macos/anaconda3/envs/tensorflow/lib/python3.6/site-packages/jieba_fast/__init__.py", line 308, in cut
    for word in cut_block(blk):
  File "/Users/macos/anaconda3/envs/tensorflow/lib/python3.6/site-packages/jieba_fast/__init__.py", line 273, in __cut_DAG
    for t in recognized:
  File "/Users/macos/anaconda3/envs/tensorflow/lib/python3.6/site-packages/jieba_fast/finalseg/__init__.py", line 97, in cut
    for word in __cut(blk):
  File "/Users/macos/anaconda3/envs/tensorflow/lib/python3.6/site-packages/jieba_fast/finalseg/__init__.py", line 69, in __cut
    prob, pos_list = _jieba_fast_functions._viterbi(sentence, 'BMES', start_P, trans_P, emit_P)
SystemError: <built-in function _viterbi> returned a result with an error set

分词的文件2500多万词 22万多行 是因为太大了吗？

**Comment by deepcs233** [comment]
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa3 in position 0: invalid start byte
> 
> The above exception was the direct cause of the following exception:

不是因为文件太大的原因，你试试把文件换个编码，换成utf8或者unicode再试一试
@songshenma

**Comment by songshenma** [comment]
我的文件本身就是UTF8编码的

**Comment by songshenma** [comment]
<img width="424" alt="2018-03-01 15 54 10" src="https://user-images.githubusercontent.com/19419803/36832972-ca893796-1d68-11e8-9930-fa96cdc323a0.png">

**Comment by deepcs233** [comment]
emmmm，我这里不能复现你的问题，方便的话你可以截取一段会导致程序出错的文本贴一下，或者发到我的邮箱shaohao97@gmail.com

**Comment by deepcs233** [comment]
@songshenma 这个issue的问题应该和你一样，已经得到解决，你可以再试一下[https://github.com/deepcs233/jieba_fast/issues/6](url)
